"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { ORDER_STATUS_LABELS } from "@/constants";
import type { OrderStatus } from "@/types";
import { toast } from "sonner";

const NEXT_STATUS: Partial<Record<OrderStatus, OrderStatus>> = {
  placed:   "confirmed",
  confirmed: "packed",
  packed:    "shipped",
  shipped:   "out_for_delivery",
  out_for_delivery: "delivered",
};

export function OrderStatusUpdater({
  orderId,
  currentStatus,
  hasTracking = false,
  trackingNumber,
  courierName,
}: {
  orderId: string;
  currentStatus: OrderStatus;
  hasTracking?: boolean;
  trackingNumber?: string | null;
  courierName?: string | null;
}) {
  const [loading, setLoading] = useState(false);
  const [note, setNote] = useState("");
  const [trackingNum, setTrackingNum] = useState("");
  const router = useRouter();

  const next = NEXT_STATUS[currentStatus];

  // Order has reached/passed "packed" but no AWB was generated (e.g. Shiprocket
  // wallet was empty at pack time). Let the admin retry without re-packing.
  const PACKED_OR_LATER: OrderStatus[] = ["packed", "shipped", "out_for_delivery"];
  const canRetryShiprocket = !hasTracking && PACKED_OR_LATER.includes(currentStatus);

  async function retryShiprocket() {
    setLoading(true);
    const res = await fetch(`/api/orders/${orderId}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ action: "retry_shiprocket" }),
    });
    const { ok, shiprocket_error } = await res.json();
    setLoading(false);
    if (shiprocket_error) {
      toast.error(`Shiprocket: ${shiprocket_error}`);
      return;
    }
    if (ok) toast.success("Tracking generated from Shiprocket");
    router.refresh();
  }

  async function update() {
    setLoading(true);
    const res = await fetch(`/api/orders/${orderId}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        status:          next,
        note:            note || undefined,
        tracking_number: trackingNum || undefined,
      }),
    });
    const { error, shiprocket_error } = await res.json();
    setLoading(false);
    if (error) { toast.error(error); return; }
    toast.success(`Order marked as ${ORDER_STATUS_LABELS[next!]}`);
    // Status moved, but Shiprocket fulfillment failed — warn so admin can retry/fix.
    if (shiprocket_error) {
      toast.warning(`Shiprocket: ${shiprocket_error}. Tracking not generated — check wallet balance / serviceability.`);
    }
    router.refresh();
  }

  async function cancelOrder() {
    if (!confirm("Cancel this order?")) return;
    setLoading(true);
    const res = await fetch(`/api/orders/${orderId}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ status: "cancelled" }),
    });
    const { error } = await res.json();
    setLoading(false);
    if (error) { toast.error(error); return; }
    toast.success("Order cancelled");
    router.refresh();
  }

  if (!next && !canRetryShiprocket && currentStatus !== "placed" && currentStatus !== "confirmed") return null;

  return (
    <div className="rounded-2xl border border-gray-100 bg-white p-5 space-y-4">
      <h2 className="font-semibold text-gray-900">Update Status</h2>
      {canRetryShiprocket && (
        <div className="rounded-lg bg-amber-50 px-3 py-2 text-xs text-amber-800 space-y-2">
          <p>No tracking number was generated for this order. After ensuring your Shiprocket wallet has balance &amp; the pincode is serviceable, retry below.</p>
          <button
            onClick={retryShiprocket}
            disabled={loading}
            className="rounded-lg bg-amber-500 px-3 py-1.5 font-semibold text-white hover:bg-amber-600 disabled:opacity-60"
          >
            {loading ? "Retrying…" : "Retry Shiprocket / Generate Tracking"}
          </button>
        </div>
      )}
      {next === "packed" && (
        <p className="rounded-lg bg-brand-50 px-3 py-2 text-xs text-brand-700">
          Marking as Packed will auto-create the Shiprocket order and assign a courier &amp; tracking number.
        </p>
      )}
      {next === "shipped" && (
        hasTracking ? (
          <div className="rounded-lg bg-green-50 px-3 py-2 text-xs text-green-800">
            Tracking already generated by Shiprocket: <span className="font-semibold">{trackingNumber}</span>
            {courierName ? ` (${courierName})` : ""}. Just click “Mark as Shipped” — no need to enter anything.
          </div>
        ) : (
          <div>
            <label className="mb-1 block text-sm font-medium text-gray-700">
              Tracking Number <span className="font-normal text-gray-400">(enter manually — Shiprocket did not auto-generate one)</span>
            </label>
            <input
              value={trackingNum}
              onChange={(e) => setTrackingNum(e.target.value)}
              placeholder="AWB / Tracking number"
              className="w-full rounded-lg border border-gray-200 px-3 py-2 text-sm focus:border-brand-400 focus:outline-none"
            />
          </div>
        )
      )}
      <div>
        <label className="mb-1 block text-sm font-medium text-gray-700">Note (optional)</label>
        <input
          value={note}
          onChange={(e) => setNote(e.target.value)}
          placeholder="e.g. Packed, dispatched via Bluedart"
          className="w-full rounded-lg border border-gray-200 px-3 py-2 text-sm focus:border-brand-400 focus:outline-none"
        />
      </div>
      <div className="flex gap-3">
        {next && (
          <button
            onClick={update}
            disabled={loading}
            className="flex-1 rounded-xl bg-brand-500 py-2.5 text-sm font-bold text-white hover:bg-brand-600 disabled:opacity-60"
          >
            {loading ? "Updating…" : `Mark as ${ORDER_STATUS_LABELS[next]}`}
          </button>
        )}
        {["placed", "confirmed"].includes(currentStatus) && (
          <button
            onClick={cancelOrder}
            disabled={loading}
            className="rounded-xl border border-red-200 px-4 py-2.5 text-sm font-medium text-red-600 hover:bg-red-50 disabled:opacity-60"
          >
            Cancel Order
          </button>
        )}
      </div>
    </div>
  );
}
